### ISSUE TITLE
hello! I have exception when connect to wifi

### ISSUE THREAD

**Issue by islavstan** [jflavio1/WifiConnector#1]
07-23 20:12:25.775 26981-26981/ua.findwifi E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: ua.findwifi, PID: 26981
                                                             java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.supplicant.STATE_CHANGE flg=0x24000010 (has extras) } in com.jflavio1.wificonnector.WifiConnector$WifiConnectionReceiver@4f6b1c8
                                                                 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:932)
                                                                 at android.os.Handler.handleCallback(Handler.java:815)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                 at android.os.Looper.loop(Looper.java:207)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                              Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.jflavio1.wificonnector.WifiConnector$WifiConnectionReceiver@fe4d261
                                                                 at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:789)
                                                                 at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1200)
                                                                 at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:576)
                                                                 at com.jflavio1.wificonnector.WifiConnector$WifiConnectionReceiver.onReceive(WifiConnector.java:727)
                                                                 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:922)
                                                                 at android.os.Handler.handleCallback(Handler.java:815) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                 at android.os.Looper.loop(Looper.java:207) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5728) 
                                                                 at java.lang.reflect.Method.invoke(Native Method)

**Comment by jflavio11** [comment]
Hi @islavstan !

Could you share your snippet for knowing how could this occurred?

👍

**Comment by islavstan** [comment]
import android.app.Service;
import android.content.Intent;
import android.net.wifi.ScanResult;
import android.net.wifi.SupplicantState;
import android.os.Binder;
import android.os.IBinder;
import android.text.TextUtils;

import com.jflavio1.wificonnector.WifiConnector;
import com.jflavio1.wificonnector.interfaces.ConnectionResultListener;

import rx.Observable;
import rx.android.schedulers.AndroidSchedulers;
import rx.schedulers.Schedulers;
import ua.findwifi.R;
import ua.findwifi.WifiApp;
import ua.findwifi.bus.RxBus;
import ua.findwifi.bus.ServiceMessageEvent;
import ua.findwifi.preferences.PreferencesProvider;
import ua.findwifi.providers.DataProvider;

public class WifiConnectorService extends Service {
    private final IBinder serviceBinder = new WifiConnectorService.RunServiceBinder();
    private WifiConnector connector;
    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        return Service.START_STICKY;
    }

    @Override
    public IBinder onBind(Intent intent) {
        return serviceBinder;
    }

    public void connectToWifi(ScanResult scanResult, String password) {
        connector = new WifiConnector(WifiApp.getInstance().getApplicationContext()
                , scanResult.SSID, scanResult.BSSID, scanResult.capabilities, password);
        connector.enableWifi();
        connector.connectToWifi(new ConnectionResultListener() {
            @Override
            public void successfulConnect(String SSID) {
                if (TextUtils.equals(SSID, String.format("\"%s\"", scanResult.SSID))) {
                    sendPointToServer(scanResult.SSID, password);
                }
            }

            @Override
            public void errorConnect(int codeReason) {

            }

            @Override
            public void onStateChange(SupplicantState supplicantState) {
            }
        });
    }

    public void unregister() {
        if (connector != null) {
            connector.unregisterListeners(connector.wifiConnectionReceiver);
        }
    }

    public class RunServiceBinder extends Binder {
        public WifiConnectorService getService() {
            return WifiConnectorService.this;
        }
    }
}


import android.content.ComponentName;
import android.content.Intent;
import android.content.ServiceConnection;
import android.net.wifi.ScanResult;
import android.os.Bundle;
import android.os.IBinder;
import android.provider.Settings;
import android.support.annotation.NonNull;
import android.support.design.widget.Snackbar;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentTransaction;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.TextView;

import com.arellomobile.mvp.MvpAppCompatActivity;
import com.arellomobile.mvp.presenter.InjectPresenter;

import ua.findwifi.R;
import ua.findwifi.screens.map.MapFragment;
import ua.findwifi.screens.wifi_list.WifiListFragment;
import ua.findwifi.services.WifiConnectorService;

public class MainActivity extends MvpAppCompatActivity implements MainActivityView {
    @InjectPresenter
    MainActivityPresenter mPresenter;
    private FrameLayout progressView;
    private Snackbar mSnackBar;
    private WifiConnectorService mWifiConnectorService;
    private ServiceConnection connection = new ServiceConnection() {
        @Override
        public void onServiceConnected(ComponentName name, IBinder service) {
            WifiConnectorService.RunServiceBinder binder = (WifiConnectorService.RunServiceBinder) service;
            mWifiConnectorService = binder.getService();
        }

        @Override
        public void onServiceDisconnected(ComponentName name) {
        }
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        progressView = (FrameLayout) findViewById(R.id.progressView);
        showWifiList();
    }

    @Override
    protected void onStart() {
        super.onStart();
        Intent i = new Intent(this, WifiConnectorService.class);
        startService(i);
        bindService(i, connection, 0);
    }

    @Override
    public void connectToWifi(ScanResult scanResult, String password) {
        if (mWifiConnectorService != null) {
            mWifiConnectorService.connectToWifi(scanResult, password);
        }
    }

    @Override
    public void showError(String error) {
        showSnackBar(error);
    }

    @Override
    public void showProgress() {
        progressView.setVisibility(View.VISIBLE);
    }

    @Override
    public void hideProgress() {
        progressView.setVisibility(View.INVISIBLE);
    }

    @Override
    public void showSnackBar(String message) {
        Snackbar.make(findViewById(android.R.id.content), message, Snackbar.LENGTH_LONG)
                .show();
    }

    @Override
    protected void onStop() {
        if (mWifiConnectorService != null) {
            mWifiConnectorService.unregister();
        }
        stopService(new Intent(this, WifiConnectorService.class));
        unbindService(connection);
        super.onStop();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
    }
}

**Comment by jflavio11** [comment]
Could you please confirm that createWifiConnectionBroadcastListener() method is not catching an exception? This could be known with the log: "Register broadcast error (Choose) .... "

Moreover, WifiConnectionReceiver is unregistered when COMPLETED or DISCONNECTED state set so please try not to explicit unregister it unless you know the connection lifecycle using registerWifiStateListener().

**Comment by islavstan** [comment]
I didn't see catch log. That's what I have
07-24 22:46:28.502 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Wifi is already enable...
07-24 22:46:28.509 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Already connected to: "Dashan" Now trying to connect to TP-LINK_BA7A
07-24 22:46:28.527 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: network id found: -1
07-24 22:46:28.634 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: networkId now: 11
07-24 22:46:28.804 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: COMPLETED
07-24 22:46:28.807 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Connection to Wifi was successfuly completed...
                                                                                   Connected to bssid: null
07-24 22:46:28.809 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Wifi enabled
07-24 22:46:28.810 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: COMPLETED
07-24 22:46:28.811 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Connection to Wifi was successfuly completed...
                                                                                   Connected to bssid: null
07-24 22:46:29.046 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: DISCONNECTED
07-24 22:46:29.047 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Disconnected... Supplicant error: -1
07-24 22:46:29.047 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: DISCONNECTED
07-24 22:46:29.047 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Disconnected... Supplicant error: -1
07-24 22:46:29.049 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: SCANNING
07-24 22:46:29.049 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: SCANNING
07-24 22:46:29.056 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: DISCONNECTED
07-24 22:46:29.056 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Disconnected... Supplicant error: -1
07-24 22:46:29.056 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: DISCONNECTED
07-24 22:46:29.057 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Disconnected... Supplicant error: -1
07-24 22:46:29.837 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATING
07-24 22:46:29.839 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATING
07-24 22:46:29.840 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATED
07-24 22:46:29.840 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATED
07-24 22:46:29.841 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: FOUR_WAY_HANDSHAKE
07-24 22:46:29.841 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: FOUR_WAY_HANDSHAKE
07-24 22:46:29.842 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: GROUP_HANDSHAKE
07-24 22:46:29.842 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: GROUP_HANDSHAKE
07-24 22:46:29.963 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: COMPLETED
07-24 22:46:29.989 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Connection to Wifi was successfuly completed...
                                                                                   Connected to bssid: 64:66:b3:45:b9:80
07-24 22:47:39.375 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Wifi is already enable...
07-24 22:47:39.381 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Already connected to: "Dashan" Now trying to connect to sta7
07-24 22:47:39.402 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: network id found: -1
07-24 22:47:39.492 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: networkId now: 12
07-24 22:47:39.637 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: COMPLETED
07-24 22:47:39.639 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Connection to Wifi was successfuly completed...
                                                                                   Connected to bssid: null
07-24 22:47:39.643 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Wifi enabled
07-24 22:47:39.649 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: COMPLETED
07-24 22:47:39.651 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Connection to Wifi was successfuly completed...
                                                                                   Connected to bssid: null
07-24 22:47:40.026 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: DISCONNECTED
07-24 22:47:40.026 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Disconnected... Supplicant error: -1
07-24 22:47:40.027 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: DISCONNECTED
07-24 22:47:40.027 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Disconnected... Supplicant error: -1
07-24 22:47:40.027 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: DISCONNECTED
07-24 22:47:40.028 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Disconnected... Supplicant error: -1
07-24 22:47:40.638 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATING
07-24 22:47:40.639 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATING
07-24 22:47:40.639 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATING
07-24 22:47:40.639 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATED
07-24 22:47:40.640 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATED
07-24 22:47:40.640 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATED
07-24 22:47:44.683 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: DISCONNECTED
07-24 22:47:44.684 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Disconnected... Supplicant error: -1
07-24 22:47:44.684 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: DISCONNECTED
07-24 22:47:44.684 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Disconnected... Supplicant error: -1
07-24 22:47:44.684 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: DISCONNECTED
07-24 22:47:44.684 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Disconnected... Supplicant error: -1
07-24 22:47:50.151 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: SCANNING
07-24 22:47:50.151 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: SCANNING
07-24 22:47:50.151 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: SCANNING
07-24 22:47:52.196 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATING
07-24 22:47:52.196 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATING
07-24 22:47:52.197 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATING
07-24 22:47:52.198 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATED
07-24 22:47:52.198 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATED
07-24 22:47:52.198 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: ASSOCIATED
07-24 22:47:52.199 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: FOUR_WAY_HANDSHAKE
07-24 22:47:52.200 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: FOUR_WAY_HANDSHAKE
07-24 22:47:52.202 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: FOUR_WAY_HANDSHAKE
07-24 22:47:52.209 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: GROUP_HANDSHAKE
07-24 22:47:52.210 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: GROUP_HANDSHAKE
07-24 22:47:52.210 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: GROUP_HANDSHAKE
07-24 22:47:52.513 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Broadcast action: COMPLETED
07-24 22:47:52.517 707-707/ua.findwifi D/com.jflavio1.wificonnector.WifiConnector: WifiConnector: Connection to Wifi was successfuly completed...
                                                                                   Connected to bssid: 42:c6:2a:50:3d:c4
07-24 22:47:52.532 707-707/ua.findwifi E/AndroidRuntime: FATAL EXCEPTION: main
                                                         Process: ua.findwifi, PID: 707
                                                         java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.supplicant.STATE_CHANGE flg=0x24000010 (has extras) } in com.jflavio1.wificonnector.WifiConnector$WifiConnectionReceiver@c64ba63
                                                             at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:932)
                                                             at android.os.Handler.handleCallback(Handler.java:815)
                                                             at android.os.Handler.dispatchMessage(Handler.java:104)
                                                             at android.os.Looper.loop(Looper.java:207)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                          Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.jflavio1.wificonnector.WifiConnector$WifiConnectionReceiver@9f21719
                                                             at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:789)
                                                             at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1200)
                                                             at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:576)
                                                             at com.jflavio1.wificonnector.WifiConnector$WifiConnectionReceiver.onReceive(WifiConnector.java:727)
                                                             at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:922)
                                                             at android.os.Handler.handleCallback(Handler.java:815) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                             at android.os.Looper.loop(Looper.java:207) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:5728) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by jflavio11** [comment]
It seems that you are registering the broadcast again when connection to access point is established (Remember "WifiConnector" automatically unregister its broadcast). Please check your activity and service lifecycle.

However, I made a little changes. Try to import this changes using:

- Gradle
`compile 'com.github.jflavio1:WifiConnector:-SNAPSHOT'`

- Maven
`<dependency>
<groupId>com.github.jflavio1</groupId>
<artifactId>WifiConnector</artifactId>
<version>-SNAPSHOT</version>
</dependency>`

Please let me know if this issue or any other occur again.

Regards,
Flavio
